prefer-workspace-packages: true
packages:
  - "./packages/**"
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@nestjs/core"
  - "@sentry/cli"
  - "@swc/core"
  - "argon2"
  - "cpu-features"
  - "esbuild"
  - "msw"
  - "protobufjs"
  - "sharp"
  - "ssh2"
ignoredBuiltDependencies:
  - "@scarf/scarf"
  - "sqlite3"

